version: "3.8"

services:
  postgres:
    image: postgres
    container_name: upc-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: upc_virtual
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
